# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}"

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/waffle-stomper/Ghostwriter/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/waffle-stomper/Ghostwriter/master/update.json"
    displayURL="https://github.com/waffle-stomper/Ghostwriter"
    logoFile="icon.png"
    credits="maester_flaminius, SortByNode, Lodish, and all of the other wonderful people I've met through Minecraft"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.ghostwriter]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.ghostwriter]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"
